import streamlit as st
from typing import Iterator, Dict, Any
from agno.agent import Agent, RunResponse
from agno.storage.workflow.sqlite import SqliteWorkflowStorage
from agno.utils.log import logger
from agno.workflow import Workflow
from agno.models.groq import Groq
from agno.tools.python import PythonTools

class CodeGenerationWorkflow(Workflow):
    description: str = "Generate, review, and execute Python code based on user input."

    def create_agents(self):
        super().__init__(
            storage=SqliteWorkflowStorage(
                table_name="code_workflow",
                db_file="tmp/code_workflows.db",
            )
        )
        self.code_generator =  Agent(
            description="""You are an expert Python code generator. 
            You take natural language instructions from the user and generate Python code that fulfills those requirements. 
            Focus on clarity, efficiency, and correctness. Only generate code. Do not explain the code. 
            Your task is to generate code that build a workflow with agents using agno library.""",
            show_tool_calls=True,
            model=Groq(id="deepseek-r1-distill-llama-70b", api_key="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", temperature=0.4),
            instructions=[
                "Carefully analyze the user's request and break it down into logical steps.",
                "Write Python code that addresses each step.",
                "Ensure the code is well-structured, readable, and uses best practices.",
                "Do not add explanations to the code.",
                "If user input is not clear, ask for clarification.",
                "Return only the code itself.",
                "If you are asked to build a workflow using agno python package then use the tools Newspaper4kTools, ExaTools, GoogleSearchTools",
                "make sure to install them in your code with pip install before",
            ],
            expected_output="Valid Python code.",
        )

        self.code_reviewer =  Agent(
            description="""You are an expert Python code reviewer. 
            You receive Python code and analyze it for potential bugs, errors, or inefficiencies. 
            Provide detailed feedback on any issues you find. Be specific with your critique. If no bugs, then return 'No bugs found' """,
            show_tool_calls=True,
            model=Groq(id="deepseek-r1-distill-llama-70b", api_key="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", temperature=0.4),
            instructions=[
                "Carefully examine the provided Python code line by line.",
                "Look for potential logical errors, syntax mistakes, or runtime issues.",
                "Check for inefficient code practices.",
                "Critique the code and provide specific feedback on how it could be improved or bugs that you found.",
                "If no bugs found then return only 'No bugs found'",
                "Explain any potential issues and how they might manifest.",
                "Only return bugs and potential issues.",
            ],
            expected_output="Detailed feedback on code issues or 'No bugs found'.",
        )
        self.code_executor = Agent(
                description="""You are a Python code executor.
                You receive Python code and execute it.
                You report the output of the code, or any errors that occur during execution.
                If execution is successful, return 'Code executed successfully' followed by the output.
                Make sure that you can install the packages using pip install if needed""",
                show_tool_calls=True,
                model=Groq(id="deepseek-r1-distill-llama-70b", api_key="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", temperature=0.4),
                tools=[PythonTools()],
                instructions=[
                "Receive Python code and execute it.",
                "Capture any output generated by the code.",
                "If the code encounters an error during execution, report the error message.",
                "If the code executes without errors, return the output of the code.",
                "If code works as expected then add at the end of the output 'Code executed successfully'",
                "If you encounter an error try to solve it by installing the missing packages with pip install",
                ],
                expected_output="Output of the executed code, or error message if execution failed.",
            )

    def execute_python_code(self, code: str) -> str:
        """Executes the given Python code and returns the output or an error message."""
        return self.code_executor.run(code).content

    def update_run_method(self):
        def run(user_input, feedback_data=None):
            
            log_container = st.empty()
            
            if feedback_data:
                logger.info(f"Feedback: {feedback_data}")
                with log_container.container():
                    st.text_area("Feedback:", value=f"Feedback: {feedback_data}", height=100)
                
                yield RunResponse(run_id=self.run_id, content=f"Feedback: {feedback_data}")
                if "bugs" in feedback_data and feedback_data["bugs"]:
                    user_input = feedback_data["bugs"]

            logger.info(f"User input: {user_input}")
            with log_container.container():
                st.text_area("User Input:", value=f"User input: {user_input}", height=100)
            yield RunResponse(run_id=self.run_id, content=f"User input: {user_input}")

            # Generate code
            logger.info("Generating code...")
            with log_container.container():
                st.text("Generating code...")
            code_generation_response: RunResponse = self.code_generator.run(
                user_input
            )
            if not code_generation_response.content:
                with log_container.container():
                    st.error("Code generation failed.")
                yield RunResponse(run_id=self.run_id, content="Code generation failed.")
                return

            generated_code = code_generation_response.content
            with log_container.container():
                st.text_area("Generated Code:", value=f"```python\n{generated_code}\n```", height=300)
            yield RunResponse(run_id=self.run_id, content=f"Generated Code:\n```python\n{generated_code}\n```")

            # Review code
            logger.info("Reviewing code...")
            with log_container.container():
                st.text("Reviewing code...")
            code_review_response: RunResponse = self.code_reviewer.run(
                generated_code
            )
            if not code_review_response.content:
                with log_container.container():
                    st.error("Code review failed.")
                yield RunResponse(run_id=self.run_id, content="Code review failed.")
                return

            review_result = code_review_response.content
            with log_container.container():
                 st.text_area("Review Result:", value=review_result, height=200)
            yield RunResponse(run_id=self.run_id, content=f"Review Result:\n{review_result}")

            # Execute code
            logger.info("Executing code...")
            with log_container.container():
                 st.text("Executing code...")
            if "No bugs found" in review_result:
                code_execution_output = self.execute_python_code(generated_code)
                with log_container.container():
                     st.text_area("Execution Result:", value=f"```\n{code_execution_output}\n```", height=300)
                yield RunResponse(run_id=self.run_id, content=f"Execution Result:\n```\n{code_execution_output}\n```")
            else:
                with log_container.container():
                    st.warning("Code contains bugs, returning to code generator")
                yield RunResponse(run_id=self.run_id, content="Code contains bugs, returning to code generator")

                new_feedback_data = {
                    "original_input": user_input,
                    "bugs": f"Bugs found: {review_result}",
                }
                yield from self._run_recursive(new_feedback_data, is_recursive_call=False)

        def _run_recursive(feedback_data: Dict[str, Any], is_recursive_call: bool) -> Iterator[RunResponse]:
            """Helper method to handle recursive calls properly."""
            # Extract the user_input from the feedback_data, and if the feedback_data includes bugs, also extract it.
            user_input = feedback_data.get("bugs", "") if feedback_data.get("bugs", "") != "" else feedback_data.get("original_input")

            if is_recursive_call:
                yield from run(user_input, feedback_data)
            else:
                yield from run(user_input, feedback_data)

        setattr(self, "run", run)
        setattr(self, "_run_recursive", _run_recursive)

    def run_workflow(self, user_input: str, feedback_data: Dict[str, Any] = None) -> Iterator[RunResponse]:
        """
        Main workflow implementation that handles the code generation process.
        """
        self.create_agents()
        self.update_run_method()
        yield from self.run(user_input, feedback_data)